version: '3.8'

services:
  fastapi:
    build:
      context: ./fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi:/app
      - ./shared:/app/shared
    container_name: fake_newsd-fastapi

  streamlit:
    build:
      context: ./streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit:/app
      - ./shared:/app/shared
    container_name: fake_newsd-streamlit
