name: 🚀 Build & Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "hv6806@gmail.com"
          password: "Harshaamity@2"

      - name: Build & push FastAPI image
        uses: docker/build-push-action@v5
        with:
          context: ./fastapi
          push: true
          tags: perni007/fake_news_api-fastapi:latest

